- name: Build container with Ansible
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: stop and remove containers
      command: docker-compose down
      ignore_errors: yes

    # Make sure to change the image name with your personal dockerhub account and reposiroty 
    - name: remove image built with dockercompose
      command: docker rmi -f ranizouaoui/frontend
      ignore_errors: yes

    - name: remove backend  image
      command: docker rmi -f ranizouaoui/backend
      ignore_errors: yes

    - name: remove analysis-servers image
      command: docker rmi -f ranizouaoui/analysis-servers
      ignore_errors: yes

    - name: remove alert server image
      command: docker rmi -f ranizouaoui/alert-server
      ignore_errors: yes
    - name: remove collect server image
      command: docker rmi -f ranizouaoui/collect-server
      ignore_errors: yes
    - name: build docker-compose
      command: docker-compose up --build

  # Use the following command if you don't know what the container name will be when created 'make sure you replace php-apache with keywords from your container name'
      # command: docker exec -i `docker ps -q --filter name=php-apache` bash -c "composer update"
